module(
    name = "perimortem",
    version = "0.1.0",
)

bazel_dep(name = "rules_cc", version = "0.2.17")
bazel_dep(name = "platforms", version = "1.0.0")
bazel_dep(name = "rules_pkg", version = "1.3.0")
bazel_dep(name = "tetro_toolchain", version = "0.1.0")
archive_override(
    module_name = "tetro_toolchain",
    sha256 = "c34c2230660426abefb7344305969b72ebb7cfe119e9adeaaa81d5533c7cd1f5",
    urls = ["https://github.com/tetrodotoxin-dev/Toolchain/releases/download/v0.1.0/tetro_toolchain-0.1.0-source.tar.gz"],
)

register_toolchains("@tetro_toolchain//:cc_toolchain_for_linux_x86_64", "@tetro_toolchain//:cc_toolchain_for_wasm32", "@tetro_toolchain//:cc_toolchain_for_windows_x64")
