module(
    name = "perimortem",
    version = "0.1.0",
)

bazel_dep(name = "rules_cc", version = "0.2.17")
bazel_dep(name = "platforms", version = "1.0.0")
bazel_dep(name = "rules_pkg", version = "1.3.0")
bazel_dep(name = "tetro_toolchain", version = "0.2.0")
archive_override(
    module_name = "tetro_toolchain",
    sha256 = "9adedaf160e804dc054d9fd611db817cedd4c822611cddd60002d62a6575780d",
    strip_prefix = "Toolchain-b7ae63f3a2539f425e6f1b1b179343b3029e3d97",
    urls = ["https://github.com/tetrodotoxin-dev/Toolchain/archive/b7ae63f3a2539f425e6f1b1b179343b3029e3d97.tar.gz"],
)

register_toolchains("@tetro_toolchain//:cc_toolchain_for_linux_x86_64", "@tetro_toolchain//:cc_toolchain_for_wasm32", "@tetro_toolchain//:cc_toolchain_for_windows_x64")
